apiVersion: v1
appVersion: 0.0.3
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: zeebe-3675-reproducer
version: 0.0.3
